drop table ANSIBLE_CONTROLLER
drop table CONDITION
drop table ROLE
drop table ROLE_OPERATE
drop table ROLE_PROFILE
drop table ROLE_ACTUAL_RESULT
drop table ROLE_EXPECT_RESULT
drop table ROLE_PROFILE_BIND
drop table ROLE_OPERATE_INPUT

--drop index ANSIBLE_CONTROLLER_AC_INDEX_UINDEX;
--drop index ANSIBLE_CONTROLLER_HOST_IP_UINDEX;
--drop index ROLE_ROLE_INDEX_UINDEX;
--drop index ROLE_EXPECT_RESULT_ROLE_OPERATE_OPERATE_DISPLAY_FK_INDEX_5;
--drop index ROLE_OPERATE_INPUT_OPERATE_INPUT_VALUE_UINDEX;
--drop index ROLE_ACTUAL_RESULT_ROLE_PROFILE_RP_INDEX_FK_INDEX_8;
--drop index ROLE_PROFILE_RP_INDEX_UINDEX;
